apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-certificate
spec:
  secretName: my-tls-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: mydeployment.me
  dnsNames:
  - mydeployment.me
